### ISSUE TITLE
Override needed

### ISSUE THREAD

**Issue by reid-spencer** [whisklabs/scalapb-playjson#2]
I tried this package because I need its functionality, but apparently it isn't working. When I include it in my libraryDependencies then my protobuf generated scala files do not compile. I get things like:

`[error] /Volumes/Code/J9/edge/ante/target/scala-2.11/src_managed/main/protobuf/com/j9tech/ante/data/EnvelopeProto.scala:109: overriding method descriptor in trait GeneratedMessageCompanion of type => com.google.protobuf.Descriptors.Descriptor;
[error]  method descriptor needs `override' modifier
[error]   def descriptor: com.google.protobuf.Descriptors.Descriptor = EnvelopeProto.descriptor.getMessageTypes.get(0)
[error]       ^
[error] 128 errors found
`
I didn't think this package affected the code generation, but perhaps it does? Anyway, this is the only issue holding me up from trying this package.

**Comment by viktortnk** [comment]
Hi @reid-spencer 
We successfully use this package in production, so it is generally working.

The problem you have is with generated sources. The only thing I can think of is there could be dependencies mismatch. This library depends on protobuf 3.1.0. Which version do you use?

**Comment by reid-spencer** [comment]
Yes, exactly. There was a very subtle mismatch between runtime library, compiler plugin, and protobuf version being used. I hadn't updated my dependencies but this library caused newer versions to be pulled in. I've resolved all that and its working like a charm now. Sorry for the false alarm.
Marking closed now.

**Comment by reid-spencer** [comment]
Oh! And, THANK YOU for this. Cut out a bunch of busy-work coding.

**Comment by viktortnk** [comment]
no problem :)
